/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.ProductController;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class CreateNewProductFrame extends javax.swing.JDialog {

    private ProductController productController;

    /**
     * Creates new form CreateNewProductFrame
     */
    public CreateNewProductFrame(java.awt.Frame parent, boolean modal, ProductController productController) {
        super(parent, modal);
        initComponents();
        this.productController = productController;
        pBook.setVisible(true);
        pMovie.setVisible(false);
        pMusic.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdBook = new javax.swing.JRadioButton();
        rdMovie = new javax.swing.JRadioButton();
        rdMusic = new javax.swing.JRadioButton();
        pBook = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lbQuantity = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbSold = new javax.swing.JLabel();
        tfBookName = new javax.swing.JTextField();
        tfBookAuthor = new javax.swing.JTextField();
        tfBookPublisher = new javax.swing.JTextField();
        tfBookQuantity = new javax.swing.JTextField();
        tfBookPrice = new javax.swing.JTextField();
        tfBookSold = new javax.swing.JTextField();
        tfBookPurchasePrice = new javax.swing.JTextField();
        lbQuantity3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        pMovie = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbName1 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lbQuantity1 = new javax.swing.JLabel();
        lbPrice1 = new javax.swing.JLabel();
        lbSold1 = new javax.swing.JLabel();
        tfMovieName = new javax.swing.JTextField();
        tfMovieDirector = new javax.swing.JTextField();
        tfMovieActors = new javax.swing.JTextField();
        tfMovieQuantity = new javax.swing.JTextField();
        tfMoviePrice = new javax.swing.JTextField();
        tfMovieSold = new javax.swing.JTextField();
        tfMoviePurchasePrice = new javax.swing.JTextField();
        lbQuantity4 = new javax.swing.JLabel();
        pMusic = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbName2 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lbQuantity2 = new javax.swing.JLabel();
        lbPrice2 = new javax.swing.JLabel();
        lbSold2 = new javax.swing.JLabel();
        tfMusicName = new javax.swing.JTextField();
        tfMusicSinger = new javax.swing.JTextField();
        tfMusicType = new javax.swing.JTextField();
        tfMusicQuantity = new javax.swing.JTextField();
        tfMusicPrice = new javax.swing.JTextField();
        tfMusicSold = new javax.swing.JTextField();
        tfMusicPurchasePrice = new javax.swing.JTextField();
        lbQuantity5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create New Product");
        setLocation(new java.awt.Point(300, 300));
        setPreferredSize(new java.awt.Dimension(419, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("1. Choose Type Of Product");

        buttonGroup1.add(rdBook);
        rdBook.setSelected(true);
        rdBook.setText("Book");
        rdBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBookActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdMovie);
        rdMovie.setText("Movie");
        rdMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMovieActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdMusic);
        rdMusic.setText("Music");
        rdMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdMusicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdBook)
                        .addGap(18, 18, 18)
                        .addComponent(rdMovie)
                        .addGap(18, 18, 18)
                        .addComponent(rdMusic))
                    .addComponent(jLabel1))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBook)
                    .addComponent(rdMovie)
                    .addComponent(rdMusic))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("2. Product Information");

        lbName.setText("Name");

        lb2.setText("Author");

        lb3.setText("Publisher");

        lbQuantity.setText("Quantity");

        lbPrice.setText("Price");

        lbSold.setText("Sold");

        lbQuantity3.setText("Purchase Price");

        javax.swing.GroupLayout pBookLayout = new javax.swing.GroupLayout(pBook);
        pBook.setLayout(pBookLayout);
        pBookLayout.setHorizontalGroup(
            pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pBookLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pBookLayout.createSequentialGroup()
                                .addComponent(lb3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pBookLayout.createSequentialGroup()
                                .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb2)
                                    .addComponent(lbName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(55, 55, 55)
                .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pBookLayout.createSequentialGroup()
                        .addComponent(lbSold)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfBookSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBookLayout.createSequentialGroup()
                        .addComponent(lbPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfBookPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBookLayout.createSequentialGroup()
                        .addComponent(lbQuantity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfBookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pBookLayout.createSequentialGroup()
                        .addComponent(lbQuantity3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfBookPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(136, 136, 136))
        );

        pBookLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfBookAuthor, tfBookName, tfBookPrice, tfBookPublisher, tfBookPurchasePrice, tfBookQuantity, tfBookSold});

        pBookLayout.setVerticalGroup(
            pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBookLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBookLayout.createSequentialGroup()
                        .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName)
                            .addComponent(tfBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb2)
                            .addComponent(tfBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb3)
                            .addComponent(tfBookPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pBookLayout.createSequentialGroup()
                        .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuantity)
                            .addComponent(tfBookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuantity3)
                            .addComponent(tfBookPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrice)
                            .addComponent(tfBookPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSold)
                            .addComponent(tfBookSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        pMovie.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("2. Product Information");

        lbName1.setText("Name");

        lb4.setText("Director");

        lb5.setText("Actors");

        lbQuantity1.setText("Quantity");

        lbPrice1.setText("Price");

        lbSold1.setText("Sold");

        lbQuantity4.setText("Purchase Price");

        javax.swing.GroupLayout pMovieLayout = new javax.swing.GroupLayout(pMovie);
        pMovie.setLayout(pMovieLayout);
        pMovieLayout.setHorizontalGroup(
            pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMovieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(pMovieLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pMovieLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lb5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfMovieActors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pMovieLayout.createSequentialGroup()
                                .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb4)
                                    .addComponent(lbName1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfMovieDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(55, 55, 55)
                .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSold1)
                    .addComponent(lbPrice1)
                    .addComponent(lbQuantity1)
                    .addComponent(lbQuantity4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMoviePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMoviePurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMovieQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMovieSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127))
        );

        pMovieLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfMovieActors, tfMovieDirector, tfMovieName, tfMoviePrice, tfMoviePurchasePrice, tfMovieQuantity, tfMovieSold});

        pMovieLayout.setVerticalGroup(
            pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMovieLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMovieLayout.createSequentialGroup()
                        .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName1)
                            .addComponent(tfMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb4)
                            .addComponent(tfMovieDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb5)
                            .addComponent(tfMovieActors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pMovieLayout.createSequentialGroup()
                        .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuantity1)
                            .addComponent(tfMovieQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuantity4)
                            .addComponent(tfMoviePurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrice1)
                            .addComponent(tfMoviePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMovieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSold1)
                            .addComponent(tfMovieSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pMusic.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("2. Product Information");

        lbName2.setText("Name");

        lb6.setText("Singer");

        lb7.setText("Type");

        lbQuantity2.setText("Quantity");

        lbPrice2.setText("Price");

        lbSold2.setText("Sold");

        tfMusicSinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMusicSingerActionPerformed(evt);
            }
        });

        lbQuantity5.setText("Purchase Price");

        javax.swing.GroupLayout pMusicLayout = new javax.swing.GroupLayout(pMusic);
        pMusic.setLayout(pMusicLayout);
        pMusicLayout.setHorizontalGroup(
            pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMusicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMusicLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62))
                    .addGroup(pMusicLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb6)
                            .addComponent(lbName2)
                            .addComponent(lb7))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfMusicType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfMusicSinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfMusicName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)))
                .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pMusicLayout.createSequentialGroup()
                        .addComponent(lbSold2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMusicSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pMusicLayout.createSequentialGroup()
                        .addComponent(lbPrice2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMusicPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMusicLayout.createSequentialGroup()
                        .addComponent(lbQuantity2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfMusicQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pMusicLayout.createSequentialGroup()
                        .addComponent(lbQuantity5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfMusicPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129))
        );

        pMusicLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfMusicName, tfMusicPrice, tfMusicPurchasePrice, tfMusicQuantity, tfMusicSinger, tfMusicSold, tfMusicType});

        pMusicLayout.setVerticalGroup(
            pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMusicLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMusicLayout.createSequentialGroup()
                        .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName2)
                            .addComponent(tfMusicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb6)
                            .addComponent(tfMusicSinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb7)
                            .addComponent(tfMusicType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pMusicLayout.createSequentialGroup()
                        .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuantity2)
                            .addComponent(tfMusicQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbQuantity5)
                            .addComponent(tfMusicPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrice2)
                            .addComponent(tfMusicPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSold2)
                            .addComponent(tfMusicSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pBook, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel)
                    .addComponent(btnReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBookActionPerformed
        pBook.setVisible(true);
        pMovie.setVisible(false);
        pMusic.setVisible(false);
        pBook.setEnabled(true);
        pMovie.setEnabled(false);
        pMusic.setEnabled(false);
    }//GEN-LAST:event_rdBookActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        int id = this.productController.getLastId() + 1;
        if (rdBook.isSelected()) {
            if (!this.validateBook()) {
                return;
            }

            this.productController.addBook(makeBookRecord(), id);
        } else if (rdMovie.isSelected()) {
            if (!this.validateMovie()) {
                return;
            }

            this.productController.addMovie(makeMovieRecord(), id);
        } else {
            if (!this.validateMusic()) {
                return;
            }

            this.productController.addMusic(makeMusicRecord(), id);
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private ArrayList<String> makeBookRecord() {
        ArrayList<String> newBook = new ArrayList<>();
        newBook.add(tfBookName.getText());
        newBook.add(tfBookAuthor.getText());
        newBook.add(tfBookPublisher.getText());
        newBook.add(tfBookQuantity.getText());
        newBook.add(tfBookPurchasePrice.getText());
        newBook.add(tfBookPrice.getText());
        newBook.add(tfBookSold.getText());
        return newBook;
    }

    private ArrayList<String> makeMovieRecord() {
        ArrayList<String> newMovie = new ArrayList<>();
        newMovie.add(tfMovieName.getText());
        newMovie.add(tfMovieDirector.getText());
        newMovie.add(tfMovieActors.getText());
        newMovie.add(tfMovieQuantity.getText());
        newMovie.add(tfBookPurchasePrice.getText());
        newMovie.add(tfMoviePrice.getText());
        newMovie.add(tfMovieSold.getText());
        return newMovie;
    }

    private ArrayList<String> makeMusicRecord() {
        ArrayList<String> newMusic = new ArrayList<>();
        newMusic.add(tfMusicName.getText());
        newMusic.add(tfMusicSinger.getText());
        newMusic.add(tfMusicType.getText());
        newMusic.add(tfMusicQuantity.getText());
        newMusic.add(tfBookPurchasePrice.getText());
        newMusic.add(tfMusicPrice.getText());
        newMusic.add(tfMusicSold.getText());
        return newMusic;
    }

    private boolean validateBook() {
        if (tfBookName.getText().isEmpty()) {
            return false;
        }
        if (tfBookAuthor.getText().isEmpty()) {
            return false;
        }
        if (tfBookPublisher.getText().isEmpty()) {
            return false;
        }
        if (tfBookQuantity.getText().isEmpty()) {
            return false;
        }
        if (tfBookPrice.getText().isEmpty()) {
            return false;
        }
        if (tfBookSold.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    private boolean validateMovie() {
        if (tfMovieName.getText().isEmpty()) {
            return false;
        }
        if (tfMovieDirector.getText().isEmpty()) {
            return false;
        }
        if (tfMovieActors.getText().isEmpty()) {
            return false;
        }
        if (tfMovieQuantity.getText().isEmpty()) {
            return false;
        }
        if (tfMoviePrice.getText().isEmpty()) {
            return false;
        }
        if (tfMovieSold.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    private boolean validateMusic() {
        if (tfMusicName.getText().isEmpty()) {
            return false;
        }
        if (tfMusicSinger.getText().isEmpty()) {
            return false;
        }
        if (tfMusicType.getText().isEmpty()) {
            return false;
        }
        if (tfMusicQuantity.getText().isEmpty()) {
            return false;
        }
        if (tfMusicPrice.getText().isEmpty()) {
            return false;
        }
        if (tfMusicSold.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearBookForm();
        clearMovieForm();
        clearMusicForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void clearBookForm() {
        tfBookName.setText("");
        tfBookAuthor.setText("");
        tfBookPublisher.setText("");
        tfBookQuantity.setText("");
        tfBookPurchasePrice.setText("");
        tfBookPrice.setText("");
        tfBookSold.setText("");
    }

    private void clearMovieForm() {
        tfMovieName.setText("");
        tfMovieDirector.setText("");
        tfMovieActors.setText("");
        tfMovieQuantity.setText("");
        tfBookPurchasePrice.setText("");
        tfMoviePrice.setText("");
        tfMovieSold.setText("");
    }

    private void clearMusicForm() {
        tfMusicName.setText("");
        tfMusicSinger.setText("");
        tfMusicType.setText("");
        tfMusicQuantity.setText("");
        tfBookPurchasePrice.setText("");
        tfMusicPrice.setText("");
        tfMusicSold.setText("");
    }
    private void rdMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMovieActionPerformed
        pMovie.setVisible(true);
        pBook.setVisible(false);
        pMusic.setVisible(false);
        pBook.setEnabled(false);
        pMovie.setEnabled(true);
        pMusic.setEnabled(false);
    }//GEN-LAST:event_rdMovieActionPerformed

    private void rdMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdMusicActionPerformed
        pMovie.setVisible(false);
        pBook.setVisible(false);
        pMusic.setVisible(true);
        pBook.setEnabled(false);
        pMovie.setEnabled(false);
        pMusic.setEnabled(true);
    }//GEN-LAST:event_rdMusicActionPerformed

    private void tfMusicSingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMusicSingerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMusicSingerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbPrice1;
    private javax.swing.JLabel lbPrice2;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbQuantity1;
    private javax.swing.JLabel lbQuantity2;
    private javax.swing.JLabel lbQuantity3;
    private javax.swing.JLabel lbQuantity4;
    private javax.swing.JLabel lbQuantity5;
    private javax.swing.JLabel lbSold;
    private javax.swing.JLabel lbSold1;
    private javax.swing.JLabel lbSold2;
    private javax.swing.JPanel pBook;
    private javax.swing.JPanel pMovie;
    private javax.swing.JPanel pMusic;
    private javax.swing.JRadioButton rdBook;
    private javax.swing.JRadioButton rdMovie;
    private javax.swing.JRadioButton rdMusic;
    private javax.swing.JTextField tfBookAuthor;
    private javax.swing.JTextField tfBookName;
    private javax.swing.JTextField tfBookPrice;
    private javax.swing.JTextField tfBookPublisher;
    private javax.swing.JTextField tfBookPurchasePrice;
    private javax.swing.JTextField tfBookQuantity;
    private javax.swing.JTextField tfBookSold;
    private javax.swing.JTextField tfMovieActors;
    private javax.swing.JTextField tfMovieDirector;
    private javax.swing.JTextField tfMovieName;
    private javax.swing.JTextField tfMoviePrice;
    private javax.swing.JTextField tfMoviePurchasePrice;
    private javax.swing.JTextField tfMovieQuantity;
    private javax.swing.JTextField tfMovieSold;
    private javax.swing.JTextField tfMusicName;
    private javax.swing.JTextField tfMusicPrice;
    private javax.swing.JTextField tfMusicPurchasePrice;
    private javax.swing.JTextField tfMusicQuantity;
    private javax.swing.JTextField tfMusicSinger;
    private javax.swing.JTextField tfMusicSold;
    private javax.swing.JTextField tfMusicType;
    // End of variables declaration//GEN-END:variables
}
