/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.BillController;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class CreateBillFrame extends javax.swing.JDialog {

    private BillController billController;

    /**
     * Creates new form CreateBillFrame
     */
    public CreateBillFrame(java.awt.Frame parent, boolean modal, BillController billController) {
        super(parent, modal);
        this.billController = billController;
        initComponents();
        pPeriodic.setVisible(true);
        pOneTime.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdPeriodic = new javax.swing.JRadioButton();
        rdOneTime = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        pPeriodic = new javax.swing.JPanel();
        tfNamePeriodic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfCostPeriodic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPeriodic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pOneTime = new javax.swing.JPanel();
        tfNameOneTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfCostOneTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfDescriptionOneTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfTenDonViThu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 300));
        setPreferredSize(new java.awt.Dimension(396, 350));

        jLabel1.setText("Thêm Hóa Đơn");

        jLabel2.setText("1. Loại");

        buttonGroup1.add(rdPeriodic);
        rdPeriodic.setSelected(true);
        rdPeriodic.setText("Định kỳ");
        rdPeriodic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPeriodicActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdOneTime);
        rdOneTime.setText("Một Lần");
        rdOneTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOneTimeActionPerformed(evt);
            }
        });

        jLabel3.setText("2. Các giá trị");

        jLabel4.setText("Tên Hóa Đơn");

        jLabel5.setText("Cost");

        tfPeriodic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPeriodicActionPerformed(evt);
            }
        });

        jLabel6.setText("Thời gian định kỳ");

        javax.swing.GroupLayout pPeriodicLayout = new javax.swing.GroupLayout(pPeriodic);
        pPeriodic.setLayout(pPeriodicLayout);
        pPeriodicLayout.setHorizontalGroup(
            pPeriodicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPeriodicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPeriodicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNamePeriodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pPeriodicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pPeriodicLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfCostPeriodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pPeriodicLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfPeriodic, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(pPeriodicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pPeriodicLayout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel4)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );

        pPeriodicLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfCostPeriodic, tfNamePeriodic, tfPeriodic});

        pPeriodicLayout.setVerticalGroup(
            pPeriodicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPeriodicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfNamePeriodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pPeriodicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCostPeriodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pPeriodicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPeriodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(pPeriodicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pPeriodicLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );

        tfNameOneTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameOneTimeActionPerformed(evt);
            }
        });

        jLabel7.setText("Tên Hóa Đơn");

        jLabel8.setText("Cost");

        jLabel9.setText("Mô tả");

        jLabel10.setText("Đơn vị Thu");

        javax.swing.GroupLayout pOneTimeLayout = new javax.swing.GroupLayout(pOneTime);
        pOneTime.setLayout(pOneTimeLayout);
        pOneTimeLayout.setHorizontalGroup(
            pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOneTimeLayout.createSequentialGroup()
                .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pOneTimeLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pOneTimeLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOneTimeLayout.createSequentialGroup()
                                .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)))
                        .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfCostOneTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfDescriptionOneTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfTenDonViThu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pOneTimeLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pOneTimeLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(tfNameOneTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        pOneTimeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfCostOneTime, tfDescriptionOneTime, tfNameOneTime, tfTenDonViThu});

        pOneTimeLayout.setVerticalGroup(
            pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOneTimeLayout.createSequentialGroup()
                .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pOneTimeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(65, 65, 65)
                        .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfTenDonViThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pOneTimeLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCostOneTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDescriptionOneTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pOneTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pOneTimeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tfNameOneTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(90, Short.MAX_VALUE)))
        );

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pPeriodic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pOneTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(rdPeriodic)
                                .addGap(39, 39, 39)
                                .addComponent(rdOneTime)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdPeriodic)
                    .addComponent(rdOneTime))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pPeriodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pOneTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnCancel)
                    .addComponent(btnCreate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdPeriodicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPeriodicActionPerformed
        pPeriodic.setVisible(true);
        pOneTime.setVisible(false);
    }//GEN-LAST:event_rdPeriodicActionPerformed

    private void tfNameOneTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameOneTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameOneTimeActionPerformed

    private void tfPeriodicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPeriodicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPeriodicActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if (rdPeriodic.isSelected()) {
            billController.addBill(makeBillPeriodicRecord(), "Periodic");
        } else {
            billController.addBill(makeBillOneTimeRecord(), "OneTime");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private ArrayList<String> makeBillPeriodicRecord() {
        ArrayList<String> newBill = new ArrayList<>();
        newBill.add(tfNamePeriodic.getText());
        newBill.add(tfCostPeriodic.getText());
        newBill.add(tfPeriodic.getText());
        return newBill;
    }

    private ArrayList<String> makeBillOneTimeRecord() {
        ArrayList<String> newBill = new ArrayList<>();
        newBill.add(tfNameOneTime.getText());
        newBill.add(tfCostOneTime.getText());
        newBill.add(tfDescriptionOneTime.getText());
        newBill.add(tfTenDonViThu.getText());
        return newBill;
    }
    private void rdOneTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOneTimeActionPerformed
        pPeriodic.setVisible(false);
        pOneTime.setVisible(true);
    }//GEN-LAST:event_rdOneTimeActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pOneTime;
    private javax.swing.JPanel pPeriodic;
    private javax.swing.JRadioButton rdOneTime;
    private javax.swing.JRadioButton rdPeriodic;
    private javax.swing.JTextField tfCostOneTime;
    private javax.swing.JTextField tfCostPeriodic;
    private javax.swing.JTextField tfDescriptionOneTime;
    private javax.swing.JTextField tfNameOneTime;
    private javax.swing.JTextField tfNamePeriodic;
    private javax.swing.JTextField tfPeriodic;
    private javax.swing.JTextField tfTenDonViThu;
    // End of variables declaration//GEN-END:variables
}
