/*//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-LINE:variables//GEN-FIRST:event_jButton1ActionPerformed//GEN-FIRST:event_jButton1ActionPerformed
 * To change this license header, choose License Headers in Project Properties.                                                                                
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.HomeController;
import mediaone.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Administrator
 */
public class HomeFrame extends javax.swing.JFrame {
    
    private HomeController homeController;
    
    /**
     * Creates new form HomeFrame
     */
    public HomeFrame(Store store) {
        initComponents();
        homeController = new HomeController(store);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeProductManagement = new javax.swing.JButton();
        homeBillManagement = new javax.swing.JButton();
        homeSellingManagement = new javax.swing.JButton();
        homeAnalysisManagement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MediaOne");
        setLocation(new java.awt.Point(300, 300));

        homeProductManagement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeProductManagement.setText("Quản Lý Sản Phẩm");
        homeProductManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeProductManagementActionPerformed(evt);
            }
        });

        homeBillManagement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeBillManagement.setText("Quản Lý Hóa Đơn");
        homeBillManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBillManagementActionPerformed(evt);
            }
        });

        homeSellingManagement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeSellingManagement.setText("Bán Hàng");
        homeSellingManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeSellingManagementActionPerformed(evt);
            }
        });

        homeAnalysisManagement.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeAnalysisManagement.setText("Thống kê");
        homeAnalysisManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeAnalysisManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeSellingManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeProductManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeBillManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeAnalysisManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeProductManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBillManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeSellingManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeAnalysisManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeSellingManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeSellingManagementActionPerformed
        new SellingManagementFrame().setVisible(true);
    }//GEN-LAST:event_homeSellingManagementActionPerformed

    private void homeProductManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeProductManagementActionPerformed
        homeController.viewProductManagement();
    }//GEN-LAST:event_homeProductManagementActionPerformed

    private void homeBillManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBillManagementActionPerformed
        new BillManagementFrame().setVisible(true);
    }//GEN-LAST:event_homeBillManagementActionPerformed

    private void homeAnalysisManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeAnalysisManagementActionPerformed
        new AnalysisManagementFrame().setVisible(true);
    }//GEN-LAST:event_homeAnalysisManagementActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeAnalysisManagement;
    private javax.swing.JButton homeBillManagement;
    private javax.swing.JButton homeProductManagement;
    private javax.swing.JButton homeSellingManagement;
    // End of variables declaration//GEN-END:variables
}
