/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.CartController;
import java.util.ArrayList;
import mediaone.Product;
import ui.presenter.ListProductTableModel;

/**
 *
 * @author Administrator
 */
public class ListProductFrame extends javax.swing.JDialog {
    
    private ListProductTableModel tblListProducTableModel;
    private CartController cartController;

    /**
     * Creates new form ListProductFrame
     *
     * @param parent
     * @param modal
     */
    public ListProductFrame(java.awt.Frame parent, boolean modal, CartController cartController) {
        super(parent, modal);
        this.cartController = cartController;
        initComponents();

        // Init model, set column name, load Data
        initTableModel();
        loadCollumn();
        loadData(cartController.getDsSP());

        // Set model and reorder for the table
        setModel();
        setReorder();
    }

    /**
     * Init Model for the Table
     */
    private void initTableModel() {
        tblListProducTableModel = new ListProductTableModel();
    }

    /**
     * Set Model for the table
     */
    private void setModel() {
        tblListProduct.setModel(tblListProducTableModel);
    }

    /**
     * Set reorder for the column in the table
     */
    private void setReorder() {
        tblListProduct.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * Load Column Name for the table
     */
    private void loadCollumn() {
        String[] columnCart = {"id", "Product Name", "Price", "Quantity"};
        this.tblListProducTableModel.setColumnIdentifiers(columnCart);
    }

    /**
     * Load Data into Table model
     */
    private void loadData(ArrayList<Product> listProducts) {
        for (int i = 0; i < listProducts.size(); i++) {
            Product temp = listProducts.get(i);
            addProductToModel(temp);
        }
    }
    
    /**
     * Function inside LoadData to add Product to Model
     * @param product 
     */
    private void addProductToModel(Product product) {
        ArrayList<String> row = new ArrayList<>();
        
        row.add(Integer.toString(product.getId()));
        row.add(product.getName());
        row.add(Integer.toString(product.getPrice()));
        row.add(Integer.toString(product.getQuantity()));
        
        tblListProducTableModel.addRow(row.toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListProduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(300, 300));

        tblListProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListProduct);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("List Product");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClose))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnClose))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        // get Id of Click Row
        int selectedRow = tblListProduct.getSelectedRow();
        
        int id = Integer.parseInt(tblListProduct.getValueAt(selectedRow, 0).toString());
        
        cartController.addProductById(id);
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListProduct;
    // End of variables declaration//GEN-END:variables
}
